name: Run flake checks
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-app-token:
    runs-on: ubuntu-latest
    environment: automation
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
  nix-matrix:
    runs-on: ubuntu-latest
    needs: get-app-token
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ needs.get-app-token.outputs.token }}
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          github-token: ${{ needs.get-app-token.outputs.token }}
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix' --accept-flake-config)"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: [get-app-token, nix-matrix]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix )}}
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ needs.get-app-token.outputs.token }}
          persist-credentials: false
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'holster'
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          github-token: ${{ needs.get-app-token.outputs.token }}
      - run: nix build -L '.#${{ matrix.attr }}' --accept-flake-config

  nix-build-aggregate:
    runs-on: ubuntu-latest
    needs: nix-build
    steps:
      - run: exit 0

  nix-build-results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Nix Build Results
    needs: [nix-build, nix-build-aggregate]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
