name: Run flake checks
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: carve
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.jadestar.dev
            extra-trusted-public-keys = cache.jadestar.dev-1:6nJfGkAZIQL8nj9kNzgXc1AJa+Eg/zv0YjZu8wX/aFM=
      - name: Build with nix-fast-build
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --max-jobs 1 \
            --eval-max-memory-size 2048 \
            --option accept-flake-config true
      - name: Get OIDC token
        id: oidc
        uses: actions/github-script@v8
        with:
          script: |
            const token = await core.getIDToken("https://niks3.jadestar.dev");
            core.setOutput("token", token);
      - name: Push to cache
        run: |
          curl -fsSL "https://github.com/Mic92/niks3/releases/latest/download/niks3_$(uname -s)_$(uname -m).tar.gz" | tar -xzf -
          ./niks3 push \
            --server-url https://niks3.jadestar.dev \
            --auth-token "${{ steps.oidc.outputs.token }}" \
            ./result-x86_64-linux.configurations/nixos/*
  auto-approve-pr:
    if: github.event_name == 'pull_request' && contains(fromJson('["dependabot[bot]", "voidscrubber-2148332231384339-17[bot]"]'), github.actor)
    needs: nix-build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
